kind: pipeline
type: docker
name: Push Image

trigger:
    event:
        - push

steps:
    - name: Build and Push Image
      image: plugins/docker
      settings:
          username:
              from_secret: docker-user
          password:
              from_secret: docker-key
          repo: randomman552/barotrauma
          tags:
              - latest