kind: pipeline
type: docker
name: Push Image

trigger:
  branch:
    - main
  event:
    exclude:
      - pull_request

steps:
  # Build image
  - name: docker-image
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: 1
    settings:
      username:
        from_secret: docker-user
      password:
        from_secret: docker-key
      repo: randomman552/barotrauma
      tags:
        - latest

  # Reporting
  - name: finished-webhook
    image: plugins/webhook
    depends_on:
      - docker-image
    settings:
      urls:
        from_secret: notification-webhook
      template: |
        {
          "title": "${DRONE_BUILD_STATUS^} for ${DRONE_REPO}",
          "message": "Build `${DRONE_BUILD_NUMBER}` triggered by `${DRONE_BUILD_EVENT}` on `${DRONE_BRANCH}` branch\n\n Commit: [`${DRONE_COMMIT_MESSAGE}`](${DRONE_COMMIT_LINK}) by ${DRONE_COMMIT_AUTHOR}\n\n[View build](${DRONE_BUILD_LINK})\n\n[View source](${DRONE_REPO_LINK})",
          "priority": 5,
          "extras": {
            "client::display": {
              "contentType": "text/markdown"
            },
            "client::notification": {
              "click": { "url": "${DRONE_BUILD_LINK}" }
            }
          }
        }
